---
version: '3.6'
services:
    traefik:
      image: library/traefik
      container_name: traefik
      command:
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--entrypoints.web.address=:8080"
        - "--log.level=DEBUG"
      ports:
        - 8080:8080
      networks:
        - testing
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      restart:
        always


    whoami2:
      # A container that exposes an API to show its IP address
      image: containous/whoami
      container_name: whoami2
      networks:
        - testing
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami2.rule=Host(`whoami2.local.host`)"
        - "traefik.http.routers.whoami2.entrypoints=web"
        - "traefik.http.routers.whoami2.service=whoami2"
        - "traefik.http.routers.whoami2.middlewares=test-auth"
        # Set auth server as forwardauth backend.
        - "traefik.http.middlewares.test-auth.forwardauth.address=http://auth:8000/"
        - "traefik.http.services.whoami2.loadbalancer.server.port=80"

    whoami:
      # A container that exposes an API to show its IP address
      image: containous/whoami
      container_name: whoami
      networks:
        - testing
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.local.host`)"
        - "traefik.http.routers.whoami.entrypoints=web"
        - "traefik.http.routers.whoami.service=whoami"
        - "traefik.http.routers.whoami.middlewares=test-auth"
        # Set auth server as forwardauth backend.
        - "traefik.http.middlewares.test-auth.forwardauth.address=http://auth:8000/"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"

    auth:
      # A container that exposes an API to show its IP address
      image: cablethief/simple-sso
      container_name: auth
      networks:
        - testing
      environment:
        - "DOMAIN=local.host"
        - "USERNAME=testing"
        - "PASSWORD=$$2a$$14$$9hNpsQYk9Y4iP4en62e.UuqW3lIlpvj6MU9ejiT44ELDTmLqA.Zha"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.auth.rule=Path(`/simple-sso-signin`)"
        # Required to be the primary rule to handle the creds coming through
        - "traefik.http.routers.auth.priority=100"
        - "traefik.http.routers.auth.entrypoints=web"
        - "traefik.http.services.auth.loadbalancer.server.port=8000"



networks:
  testing:
    name: testing
    driver: bridge
